### ISSUE TITLE
Use default import options, "jkanban.min.js" note type is not correct

### ISSUE THREAD

**Issue by hxchtiewei** [CyrilLeblanc/trilium-kanban#7]
Use default import options,  import zip ,the "jkanban.min.js" note type is files.
![图片](https://github.com/CyrilLeblanc/trilium-kanban/assets/48231900/d08664ab-0a01-4f7f-ad47-f000554e0dd0)

I delete the  "jkanban.min.js"  and import the  "jkanban.min.js" again, note type now is JS frontend.
![图片](https://github.com/CyrilLeblanc/trilium-kanban/assets/48231900/7cdc440e-feb9-4995-a018-5d25ed123165)

**Comment by CyrilLeblanc** [comment]
Hello, it should be working even in "file" type.  Did it not works for you if it's type is not "Javascript frontend" ?

**Comment by hxchtiewei** [comment]
> Hello, it should be working even in "file" type. Did it not works for you if it's type is not "Javascript frontend" ?

it is so strange...i reinstall again ,it now works.
but create a Kanban view using the template need add a "~renderNote=" relation.

**Comment by CyrilLeblanc** [comment]
That's good to know 🤔 this seems to be related to this [issues](https://github.com/CyrilLeblanc/trilium-kanban/issues/8).

I will have to do some research on a fresh install.
