### ISSUE TITLE
This help note is shown because this note of type Render HTML doesn't have required relation to function properly.

### ISSUE THREAD

**Issue by fjfzywn** [CyrilLeblanc/trilium-kanban#8]
This help note is shown because this note of type Render HTML doesn't have required relation to function properly.

Render HTML note type is used for [scripting](https://github.com/zadam/trilium/wiki/Scripts). In short, you have a HTML code note (optionally with some JavaScript) and this note will render it. To make it work, you need to define a [relation](https://github.com/zadam/trilium/wiki/Attributes) called "renderNote" pointing to the HTML note to render.

**Comment by CyrilLeblanc** [comment]
Hello I'm assuming this is the error message you got on the kanban view when rendering it.
Do you have any more information ? How did you created your kanban view ? 
What version did you install ?
Did this happen after an update of the view ?

**Comment by CyrilLeblanc** [comment]
It seem that should add this relation on the template "Kanban view".

`~renderNote=kanban`

As specified in this [comment](https://github.com/CyrilLeblanc/trilium-kanban/issues/7#issuecomment-1851573790)

**Comment by CyrilLeblanc** [comment]
After some research it seem that just importing the archive is not enough.
You also have to edit an attribute on the `Kanban Integration/Templates/Kanban View`. 
Set the `~disabled:renderNote=kanban` into `~renderNote=kanban`.

Or import the note again with `Safe mode` unchecked when importing.

I will update the installation documentation ASAP.
