### ISSUE TITLE
Is it passible to add color and icon?

### ISSUE THREAD

**Issue by liuxiawei** [CyrilLeblanc/trilium-kanban#9]
The project is amazing! I love it, But when I use it , I think it is important to  add color and icon in todo list. Is it passible to add color and icon?

**Comment by CyrilLeblanc** [comment]
I think it's a good idea. I will work on that this weekend !

**Comment by CyrilLeblanc** [comment]
And it's done ! Check [latest release](https://github.com/CyrilLeblanc/trilium-kanban/releases/tag/0.4) to download it. 
For the next update I will work on an easier way to update. Sorry for that :x

**Comment by liuxiawei** [comment]
Great Work! Thanks you !
